import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Nav from "@/components/nav/nav.jsx";
import ProgressBar from "@/components/progressbar/progressbar";
import Socials from "@/components/socials/socials";
import MouseTrail from "@/components/mouseTrail/MouseTrail";

import { Analytics } from "@vercel/analytics/next";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Johnson Berisha",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        {children}
        <ProgressBar />
        <Nav />
        <Socials />
        <MouseTrail />

        <Analytics />
      </body>
    </html>
  );
}
